spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace